version: "3.9"

services:
  bank_slip_app:
    build: ./build
    container_name: bank_slip_app
    restart: always
    tty: true
    environment:
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
    command: bash /entrypoint.sh
    mem_limit: 1024m
    mem_reservation: 128M
    cpus: 1.5
    ports:
      - $APP_PORT:$APP_PORT
    volumes:
      - ../:/app
    networks:
      - bank_slip_app
    depends_on:
      - bank_slip_db

  bank_slip_db:
    image: postgres:15-alpine
    container_name: bank_slip_db
    restart: always
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.9
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - /tmp/bank_slip_db:/var/lib/postgresql/data
      - ./build/postgresql:/docker-entrypoint-initdb.d
    networks:
      - bank_slip_app

networks:
  bank_slip_app:
